// Mock users for testing
export const mockUsers = [
  {
    id: "user-1",
    email: "john.doe@example.com",
    full_name: "John Doe",
    age: 28,
    weight: 75.5,
    height: 180,
    blood_type: "O+",
    medical_conditions: ["Hypertension", "Anxiety"],
    medications: ["Lisinopril 10mg", "Sertraline 50mg"],
    allergies: ["Peanuts", "Shellfish"],
    stress_threshold_low: 25,
    stress_threshold_medium: 55,
    stress_threshold_high: 75,
    activity_level: "moderately_active",
    created_at: "2023-01-15T10:00:00Z",
  },
  {
    id: "user-2",
    email: "sarah.smith@example.com",
    full_name: "Sarah Smith",
    age: 35,
    weight: 62.0,
    height: 165,
    blood_type: "A+",
    medical_conditions: ["Type 2 Diabetes", "Migraines"],
    medications: ["Metformin 1000mg", "Sumatriptan 50mg"],
    allergies: ["Latex"],
    stress_threshold_low: 30,
    stress_threshold_medium: 60,
    stress_threshold_high: 80,
    activity_level: "lightly_active",
    created_at: "2022-08-10T08:30:00Z",
  },
  {
    id: "user-3",
    email: "mike.johnson@example.com",
    full_name: "Mike Johnson",
    age: 42,
    weight: 88.2,
    height: 190,
    blood_type: "B+",
    medical_conditions: ["High Cholesterol", "Sleep Apnea"],
    medications: ["Atorvastatin 20mg", "CPAP therapy"],
    allergies: ["Dust mites", "Pollen"],
    stress_threshold_low: 35,
    stress_threshold_medium: 65,
    stress_threshold_high: 85,
    activity_level: "sedentary",
    created_at: "2023-03-20T11:15:00Z",
  },
  {
    id: "user-4",
    email: "emily.brown@example.com",
    full_name: "Emily Brown",
    age: 24,
    weight: 58.0,
    height: 160,
    blood_type: "AB+",
    medical_conditions: ["Asthma", "Seasonal Allergies"],
    medications: ["Albuterol inhaler", "Claritin 10mg"],
    allergies: ["Cats", "Grass pollen"],
    stress_threshold_low: 20,
    stress_threshold_medium: 50,
    stress_threshold_high: 70,
    activity_level: "very_active",
    created_at: "2020-05-12T13:45:00Z",
  },
  {
    id: "user-5",
    email: "david.wilson@example.com",
    full_name: "David Wilson",
    age: 51,
    weight: 92.5,
    height: 185,
    blood_type: "O-",
    medical_conditions: ["Arthritis", "Depression"],
    medications: ["Ibuprofen 400mg", "Fluoxetine 20mg"],
    allergies: ["Aspirin"],
    stress_threshold_low: 40,
    stress_threshold_medium: 70,
    stress_threshold_high: 90,
    activity_level: "lightly_active",
    created_at: "2021-11-08T09:20:00Z",
  },
];

// Mock health records for testing
export const mockHealthRecords = [
  {
    id: "health-1",
    user_id: "user-1",
    condition: "Hypertension",
    diagnosis_date: "2023-01-15",
    severity: "moderate",
    status: "active",
    symptoms: ["Headaches", "Dizziness", "Chest pain"],
    medications: ["Lisinopril 10mg", "Amlodipine 5mg"],
    notes:
      "Patient responds well to ACE inhibitors. Monitor blood pressure weekly.",
    created_at: "2023-01-15T10:00:00Z",
    updated_at: "2024-01-10T14:30:00Z",
  },
  {
    id: "health-2",
    user_id: "user-1",
    condition: "Generalized Anxiety Disorder",
    diagnosis_date: "2023-03-20",
    severity: "mild",
    status: "active",
    symptoms: ["Excessive worry", "Restlessness", "Fatigue"],
    medications: ["Sertraline 50mg"],
    notes: "Stress management techniques and regular exercise recommended.",
    created_at: "2023-03-20T11:15:00Z",
    updated_at: "2023-12-05T09:45:00Z",
  },
  {
    id: "health-3",
    user_id: "user-2",
    condition: "Type 2 Diabetes",
    diagnosis_date: "2022-08-10",
    severity: "moderate",
    status: "active",
    symptoms: ["Increased thirst", "Frequent urination", "Fatigue"],
    medications: ["Metformin 1000mg", "Glipizide 5mg"],
    notes:
      "HbA1c levels improving with medication and diet changes. Continue monitoring.",
    created_at: "2022-08-10T08:30:00Z",
    updated_at: "2024-01-05T16:20:00Z",
  },
  {
    id: "health-4",
    user_id: "user-2",
    condition: "Chronic Migraines",
    diagnosis_date: "2023-05-15",
    severity: "moderate",
    status: "active",
    symptoms: ["Severe headaches", "Light sensitivity", "Nausea"],
    medications: ["Sumatriptan 50mg", "Topiramate 25mg"],
    notes:
      "Trigger identification ongoing. Recommend stress reduction and regular sleep schedule.",
    created_at: "2023-05-15T16:45:00Z",
    updated_at: "2024-01-08T11:20:00Z",
  },
  {
    id: "health-5",
    user_id: "user-3",
    condition: "High Cholesterol",
    diagnosis_date: "2023-01-10",
    severity: "moderate",
    status: "active",
    symptoms: ["None visible", "Discovered during routine check"],
    medications: ["Atorvastatin 20mg"],
    notes:
      "Diet modification and exercise program initiated. Recheck lipid panel in 3 months.",
    created_at: "2023-01-10T14:30:00Z",
    updated_at: "2023-11-22T09:15:00Z",
  },
  {
    id: "health-6",
    user_id: "user-3",
    condition: "Sleep Apnea",
    diagnosis_date: "2022-11-20",
    severity: "severe",
    status: "active",
    symptoms: ["Loud snoring", "Daytime fatigue", "Morning headaches"],
    medications: ["CPAP therapy nightly"],
    notes:
      "Compliance with CPAP therapy excellent. Sleep quality significantly improved.",
    created_at: "2022-11-20T10:30:00Z",
    updated_at: "2024-01-03T15:45:00Z",
  },
  {
    id: "health-7",
    user_id: "user-4",
    condition: "Asthma",
    diagnosis_date: "2020-05-12",
    severity: "mild",
    status: "active",
    symptoms: ["Shortness of breath", "Wheezing", "Chest tightness"],
    medications: ["Albuterol inhaler", "Fluticasone inhaler"],
    notes:
      "Exercise-induced asthma. Use rescue inhaler before physical activity.",
    created_at: "2020-05-12T13:45:00Z",
    updated_at: "2023-11-18T10:15:00Z",
  },
  {
    id: "health-8",
    user_id: "user-4",
    condition: "Seasonal Allergies",
    diagnosis_date: "2021-04-08",
    severity: "mild",
    status: "seasonal",
    symptoms: ["Sneezing", "Runny nose", "Itchy eyes"],
    medications: ["Claritin 10mg", "Nasal spray"],
    notes:
      "Symptoms typically worsen in spring and fall. Preventive treatment effective.",
    created_at: "2021-04-08T14:20:00Z",
    updated_at: "2023-10-22T11:30:00Z",
  },
  {
    id: "health-9",
    user_id: "user-5",
    condition: "Osteoarthritis",
    diagnosis_date: "2021-09-15",
    severity: "moderate",
    status: "active",
    symptoms: ["Joint pain", "Stiffness", "Reduced mobility"],
    medications: ["Ibuprofen 400mg", "Glucosamine supplements"],
    notes:
      "Physical therapy recommended. Pain management through NSAIDs and activity modification.",
    created_at: "2021-09-15T11:00:00Z",
    updated_at: "2023-12-20T14:30:00Z",
  },
  {
    id: "health-10",
    user_id: "user-5",
    condition: "Major Depressive Disorder",
    diagnosis_date: "2022-03-10",
    severity: "moderate",
    status: "active",
    symptoms: ["Persistent sadness", "Loss of interest", "Fatigue"],
    medications: ["Fluoxetine 20mg"],
    notes:
      "Therapy sessions weekly. Gradual improvement with medication and counseling.",
    created_at: "2022-03-10T09:30:00Z",
    updated_at: "2024-01-12T16:15:00Z",
  },
];

// Mock stress detection data for testing
export const mockStressData = [
  {
    id: "stress-1",
    user_id: "user-1",
    timestamp: "2024-01-15T09:30:00Z",
    stress_level: 75,
    heart_rate: 88,
    gsr_value: 12.5,
    temperature: 36.8,
    emotion_detected: "anxious",
    confidence: 0.85,
    triggers: ["work deadline", "traffic"],
    recommendations: ["Deep breathing", "Take a break"],
  },
  {
    id: "stress-2",
    user_id: "user-2",
    timestamp: "2024-01-15T14:20:00Z",
    stress_level: 45,
    heart_rate: 72,
    gsr_value: 8.2,
    temperature: 36.5,
    emotion_detected: "neutral",
    confidence: 0.92,
    triggers: [],
    recommendations: ["Maintain current state"],
  },
  {
    id: "stress-3",
    user_id: "user-3",
    timestamp: "2024-01-15T18:45:00Z",
    stress_level: 85,
    heart_rate: 95,
    gsr_value: 15.8,
    temperature: 37.1,
    emotion_detected: "stressed",
    confidence: 0.91,
    triggers: ["family argument", "financial concerns"],
    recommendations: ["Progressive muscle relaxation", "Call support person"],
  },
  {
    id: "stress-4",
    user_id: "user-4",
    timestamp: "2024-01-15T12:15:00Z",
    stress_level: 25,
    heart_rate: 68,
    gsr_value: 6.1,
    temperature: 36.4,
    emotion_detected: "happy",
    confidence: 0.89,
    triggers: [],
    recommendations: ["Continue current activities"],
  },
  {
    id: "stress-5",
    user_id: "user-5",
    timestamp: "2024-01-15T20:30:00Z",
    stress_level: 60,
    heart_rate: 82,
    gsr_value: 10.3,
    temperature: 36.9,
    emotion_detected: "tired",
    confidence: 0.78,
    triggers: ["long work day", "joint pain"],
    recommendations: ["Rest", "Take pain medication", "Early bedtime"],
  },
];

// Mock chat history for testing
export const mockChatHistory = [
  {
    id: "chat-1",
    user_id: "user-1",
    session_id: "session-1",
    message_type: "user",
    content: "I've been feeling really stressed lately. Can you help?",
    created_at: "2024-01-07T10:15:00Z",
  },
  {
    id: "chat-2",
    user_id: "user-1",
    session_id: "session-1",
    message_type: "assistant",
    content:
      "I understand you're feeling stressed. Based on your recent data, I can see your stress levels have been elevated. Here are some techniques that might help: 1) Deep breathing exercises, 2) Progressive muscle relaxation, 3) Short walks outside. Would you like me to guide you through any of these?",
    created_at: "2024-01-07T10:15:30Z",
  },
  {
    id: "chat-3",
    user_id: "user-1",
    session_id: "session-1",
    message_type: "user",
    content: "Yes, please guide me through deep breathing exercises.",
    created_at: "2024-01-07T10:16:00Z",
  },
  {
    id: "chat-4",
    user_id: "user-1",
    session_id: "session-1",
    message_type: "assistant",
    content:
      "Great choice! Let's do a simple 4-7-8 breathing exercise: 1) Inhale through your nose for 4 counts, 2) Hold your breath for 7 counts, 3) Exhale through your mouth for 8 counts. Repeat this 3-4 times. Focus on making your exhale longer than your inhale - this activates your parasympathetic nervous system and helps reduce stress.",
    created_at: "2024-01-07T10:16:15Z",
  },
  {
    id: "chat-5",
    user_id: "user-2",
    session_id: "session-2",
    message_type: "user",
    content:
      "My heart rate seems higher than usual today. Should I be concerned?",
    created_at: "2024-01-07T14:30:00Z",
  },
  {
    id: "chat-6",
    user_id: "user-2",
    session_id: "session-2",
    message_type: "assistant",
    content:
      "I can see your heart rate has been slightly elevated. A few factors could contribute to this: caffeine intake, physical activity, stress, or even room temperature. Your current reading of 78 bpm is still within normal range for your age group (60-100 bpm). However, if you're experiencing chest pain, dizziness, or shortness of breath, please consult a healthcare provider immediately.",
    created_at: "2024-01-07T14:30:25Z",
  },
  {
    id: "chat-7",
    user_id: "user-3",
    session_id: "session-3",
    message_type: "user",
    content: "I'm having trouble sleeping and it's affecting my stress levels.",
    created_at: "2024-01-08T22:45:00Z",
  },
  {
    id: "chat-8",
    user_id: "user-3",
    session_id: "session-3",
    message_type: "assistant",
    content:
      "I notice you have sleep apnea and are using CPAP therapy. Poor sleep can definitely increase stress levels. Here are some additional sleep hygiene tips: 1) Maintain consistent bedtime, 2) Avoid caffeine after 2PM, 3) Create a relaxing bedtime routine, 4) Ensure your CPAP mask fits properly. Have you been consistent with your CPAP usage?",
    created_at: "2024-01-08T22:45:30Z",
  },
  {
    id: "chat-9",
    user_id: "user-4",
    session_id: "session-4",
    message_type: "user",
    content:
      "I'm feeling anxious about an upcoming presentation. Any quick tips?",
    created_at: "2024-01-09T08:20:00Z",
  },
  {
    id: "chat-10",
    user_id: "user-4",
    session_id: "session-4",
    message_type: "assistant",
    content:
      "Presentation anxiety is very common! Here are some quick techniques: 1) Practice the 'box breathing' technique (4-4-4-4 count), 2) Visualize success, 3) Do power poses for 2 minutes before presenting, 4) Remember that the audience wants you to succeed. Your current stress levels look manageable. You've got this!",
    created_at: "2024-01-09T08:20:25Z",
  },
  {
    id: "chat-11",
    user_id: "user-5",
    session_id: "session-5",
    message_type: "user",
    content: "My arthritis pain is worse today and it's making me feel down.",
    created_at: "2024-01-10T16:30:00Z",
  },
  {
    id: "chat-12",
    user_id: "user-5",
    session_id: "session-5",
    message_type: "assistant",
    content:
      "I'm sorry you're experiencing increased pain today. Chronic pain can definitely impact mood and stress levels. Consider: 1) Gentle stretching or warm bath, 2) Taking your prescribed pain medication if needed, 3) Practice mindfulness to cope with pain, 4) Contact your doctor if pain persists. Remember, it's okay to have difficult days - you're managing both arthritis and depression with strength.",
    created_at: "2024-01-10T16:30:40Z",
  },
];

// Mock biometric readings for testing
export const mockBiometricReadings = [
  {
    id: "bio-1",
    user_id: "user-1",
    timestamp: "2024-01-15T09:00:00Z",
    heart_rate: 72,
    gsr_value: 8.5,
    temperature: 36.6,
    blood_pressure_systolic: 125,
    blood_pressure_diastolic: 82,
    steps: 3250,
    calories_burned: 180,
  },
  {
    id: "bio-2",
    user_id: "user-1",
    timestamp: "2024-01-15T12:00:00Z",
    heart_rate: 88,
    gsr_value: 12.3,
    temperature: 36.8,
    blood_pressure_systolic: 135,
    blood_pressure_diastolic: 88,
    steps: 5200,
    calories_burned: 290,
  },
  {
    id: "bio-3",
    user_id: "user-2",
    timestamp: "2024-01-15T14:30:00Z",
    heart_rate: 76,
    gsr_value: 9.1,
    temperature: 36.5,
    blood_pressure_systolic: 118,
    blood_pressure_diastolic: 75,
    steps: 4800,
    calories_burned: 220,
  },
  {
    id: "bio-4",
    user_id: "user-3",
    timestamp: "2024-01-15T19:00:00Z",
    heart_rate: 95,
    gsr_value: 15.2,
    temperature: 37.0,
    blood_pressure_systolic: 145,
    blood_pressure_diastolic: 92,
    steps: 2100,
    calories_burned: 150,
  },
  {
    id: "bio-5",
    user_id: "user-4",
    timestamp: "2024-01-15T11:45:00Z",
    heart_rate: 65,
    gsr_value: 6.8,
    temperature: 36.4,
    blood_pressure_systolic: 110,
    blood_pressure_diastolic: 70,
    steps: 8500,
    calories_burned: 420,
  },
  {
    id: "bio-6",
    user_id: "user-5",
    timestamp: "2024-01-15T21:00:00Z",
    heart_rate: 82,
    gsr_value: 10.7,
    temperature: 36.9,
    blood_pressure_systolic: 128,
    blood_pressure_diastolic: 78,
    steps: 1800,
    calories_burned: 125,
  },
];
