// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unwxteyecpgcvrhqqbgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVud3h0ZXllY3BnY3ZyaHFxYmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MzA0OTUsImV4cCI6MjA2NjEwNjQ5NX0.UihP9261B2Ibq-ejmjwH-Dahi9xp-RddEQD8fI2FRQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);